import { useCallback, useEffect, useRef, useState } from 'react';
import type { VideoCaptionLine, Word } from '../types';
import { useYouTubePlayer } from '../hooks/useYouTubePlayer';
import { buildScriptText, keywordsToWords } from '../utils/customVocabulary';
import { parseYoutubeVideoId } from '../utils/youtube';
import { fetchYoutubeCaptions } from '../utils/youtubeCaptions';
import { translateLinesToEnglish, translateLinesToKorean } from '../utils/translate';
import { extractVideoKeywords, type VideoKeyword } from '../utils/videoKeywords';
import { findWordInBank } from '../utils/words';

function uid() {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function formatTime(sec: number) {
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m}:${s.toString().padStart(2, '0')}`;
}

interface VideoLearnTabProps {
  savedWordIds: string[];
  customWords: Word[];
  onSaveVideoWords: (words: Word[]) => Promise<void>;
}

export function VideoLearnTab({
  savedWordIds,
  customWords,
  onSaveVideoWords,
}: VideoLearnTabProps) {
  const [url, setUrl] = useState('');
  const [videoId, setVideoId] = useState<string | null>(null);
  const [captions, setCaptions] = useState<VideoCaptionLine[]>([]);
  const [scriptText, setScriptText] = useState('');
  const [keywords, setKeywords] = useState<VideoKeyword[]>([]);
  const [loading, setLoading] = useState(false);
  const [translating, setTranslating] = useState(false);
  const [savingWords, setSavingWords] = useState(false);
  const [translateProgress, setTranslateProgress] = useState('');
  const [saveWordsMsg, setSaveWordsMsg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [captionNotice, setCaptionNotice] = useState<string | null>(null);

  const playerHostRef = useRef<HTMLDivElement>(null);
  const scriptRef = useRef<HTMLDivElement>(null);

  const { ready, playing, currentTime, loadVideo, seekTo } = useYouTubePlayer(playerHostRef);

  const activeIndex = captions.findIndex(
    (c) => currentTime >= c.start && currentTime < c.start + c.duration,
  );

  const isWordSaved = useCallback(
    (term: string) => {
      const key = term.toLowerCase();
      if (customWords.some((w) => w.word.toLowerCase() === key)) return true;
      const bank = findWordInBank(term);
      if (bank && savedWordIds.includes(bank.id)) return true;
      return false;
    },
    [customWords, savedWordIds],
  );

  const updateScriptAndKeywords = useCallback((lines: VideoCaptionLine[]) => {
    setScriptText(buildScriptText(lines));
    const english = lines
      .map((l) => l.text)
      .filter((t) => t && t !== '번역 중…' && !t.startsWith('('));
    setKeywords(extractVideoKeywords(english));
  }, []);

  useEffect(() => {
    if (captions.length > 0 && !captions.some((c) => c.textKo === '번역 중…')) {
      updateScriptAndKeywords(captions);
    }
  }, [captions, updateScriptAndKeywords]);

  useEffect(() => {
    if (activeIndex < 0 || !scriptRef.current) return;
    const el = scriptRef.current.querySelector<HTMLElement>(`[data-line="${activeIndex}"]`);
    el?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  }, [activeIndex]);

  const handlePlay = useCallback(async () => {
    const id = parseYoutubeVideoId(url);
    if (!id) {
      setError('YouTube 링크 또는 11자리 영상 ID를 입력해 주세요.');
      return;
    }

    setError(null);
    setCaptionNotice(null);
    setSaveWordsMsg(null);
    setLoading(true);
    setCaptions([]);
    setScriptText('');
    setKeywords([]);
    setVideoId(null);

    try {
      setVideoId(id);
      await loadVideo(id);

      const captionResult = await fetchYoutubeCaptions(id);
      if (!captionResult) {
        setCaptionNotice(
          '이 영상에는 YouTube 자막이 없어 영상만 재생됩니다. YouTube에서 자막(자동 생성 포함)을 켠 영상이면 스크립트를 불러올 수 있습니다.',
        );
        return;
      }

      const { lines: raw, sourceLang, isAutoGenerated } = captionResult;
      const isKoreanSource = sourceLang === 'ko';

      const baseLines: VideoCaptionLine[] = raw.map((line) => ({
        ...line,
        id: uid(),
        text: isKoreanSource ? '번역 중…' : line.text,
        textKo: isKoreanSource ? line.text : '번역 중…',
      }));
      setCaptions(baseLines);
      if (!isKoreanSource) updateScriptAndKeywords(baseLines);

      if (isAutoGenerated) {
        setCaptionNotice('YouTube 자동 생성 자막을 불러왔습니다.');
      }

      setTranslating(true);
      setTranslateProgress('0%');
      const translateJob = isKoreanSource
        ? translateLinesToEnglish(
            raw.map((c) => c.text),
            (done, total) => setTranslateProgress(`${Math.round((done / total) * 100)}%`),
          ).then((en) => {
            setCaptions((prev) => {
              const next = prev.map((line, i) => ({ ...line, text: en[i] ?? line.text }));
              updateScriptAndKeywords(next);
              return next;
            });
          })
        : translateLinesToKorean(
            raw.map((c) => c.text),
            (done, total) => setTranslateProgress(`${Math.round((done / total) * 100)}%`),
          ).then((ko) => {
            setCaptions((prev) => {
              const next = prev.map((line, i) => ({ ...line, textKo: ko[i] ?? line.textKo }));
              updateScriptAndKeywords(next);
              return next;
            });
          });

      void translateJob
        .catch(() => {
          setCaptions((prev) => {
            const next = prev.map((line) => ({
              ...line,
              text: line.text === '번역 중…' ? '(번역 실패)' : line.text,
              textKo: line.textKo === '번역 중…' ? '(번역 실패)' : line.textKo,
            }));
            updateScriptAndKeywords(next);
            return next;
          });
        })
        .finally(() => {
          setTranslating(false);
          setTranslateProgress('');
        });
    } catch (e) {
      setError(e instanceof Error ? e.message : '영상을 불러오지 못했습니다.');
      setVideoId(null);
    } finally {
      setLoading(false);
    }
  }, [url, loadVideo, updateScriptAndKeywords]);

  const handleSaveKeywords = useCallback(async () => {
    if (!videoId || keywords.length === 0) return;
    setSavingWords(true);
    setSaveWordsMsg(null);
    try {
      const captionMap = new Map(
        captions.map((c) => [c.text.toLowerCase(), { exampleKo: c.textKo }]),
      );
      const words = await keywordsToWords(keywords, videoId, captionMap);
      await onSaveVideoWords(words);
      const n = words.length;
      setSaveWordsMsg(`주요 단어 ${n}개를 나의 단어장에 저장했습니다.`);
    } catch {
      setSaveWordsMsg('단어 저장에 실패했습니다. 잠시 후 다시 시도해 주세요.');
    } finally {
      setSavingWords(false);
    }
  }, [videoId, keywords, captions, onSaveVideoWords]);

  return (
    <section className="video-learn-tab">
      <div className="video-url-bar">
        <input
          type="url"
          className="video-url-input"
          placeholder="YouTube 링크 붙여넣기 (예: https://youtu.be/...)"
          value={url}
          onChange={(e) => setUrl(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && void handlePlay()}
          enterKeyHint="go"
          autoCapitalize="off"
          autoCorrect="off"
        />
        <button
          type="button"
          className="video-play-btn"
          onClick={() => void handlePlay()}
          disabled={loading || !url.trim()}
        >
          {loading ? '불러오는 중…' : '▶ 재생'}
        </button>
      </div>

      {error && <p className="video-error">{error}</p>}
      {captionNotice && !error && <p className="video-notice">{captionNotice}</p>}
      {saveWordsMsg && <p className="video-save-msg">{saveWordsMsg}</p>}

      <div className="video-player-wrap">
        <div
          ref={playerHostRef}
          className={`video-player-host ${videoId ? 'active' : ''}`}
          aria-label="YouTube 영상 플레이어"
        />
        {!videoId && !loading && (
          <div className="video-player-placeholder">
            <span>🎬</span>
            <p>링크 입력 후 재생 버튼을 눌러 주세요</p>
            <small>YouTube 자막(자동 생성 포함)이 있으면 스크립트·주요 단어 추출</small>
          </div>
        )}
      </div>

      {videoId && (
        <div className="video-meta">
          <span>{ready ? (playing ? '재생 중' : '일시정지') : '플레이어 준비 중'}</span>
          {translating && <span className="video-translate-status">번역 {translateProgress}</span>}
        </div>
      )}

      {scriptText && (
        <div className="video-script-box">
          <label className="video-script-label" htmlFor="video-script-text">
            자막 스크립트 (영어 + 한국어)
          </label>
          <textarea
            id="video-script-text"
            className="video-script-textarea"
            readOnly
            value={scriptText}
            rows={6}
          />
        </div>
      )}

      {keywords.length > 0 && (
        <div className="video-keywords-panel">
          <div className="video-keywords-head">
            <h3>주요 단어</h3>
            <button
              type="button"
              className="video-save-words-btn"
              onClick={() => void handleSaveKeywords()}
              disabled={savingWords || translating}
            >
              {savingWords ? '저장 중…' : '📚 단어장에 저장'}
            </button>
          </div>
          <div className="video-keyword-chips">
            {keywords.map((kw) => {
              const saved = isWordSaved(kw.word);
              return (
                <span
                  key={kw.word}
                  className={`video-keyword-chip ${saved ? 'saved' : ''}`}
                  title={kw.example}
                >
                  {kw.word}
                  {kw.count > 1 ? ` ×${kw.count}` : ''}
                  {saved ? ' ✓' : ''}
                </span>
              );
            })}
          </div>
        </div>
      )}

      <div className="video-script-panel" ref={scriptRef}>
        <h3 className="video-script-title">구간별 자막 (탭하면 이동)</h3>
        {captions.length === 0 && !loading && videoId && (
          <p className="video-script-empty">자막이 없어 구간별 목록을 표시할 수 없습니다.</p>
        )}
        {captions.length === 0 && !loading && !videoId && (
          <p className="video-script-empty">재생하면 자막과 번역이 표시됩니다.</p>
        )}
        {captions.map((line, index) => {
          const active = index === activeIndex;
          return (
            <button
              key={line.id}
              type="button"
              data-line={index}
              className={`video-script-line ${active ? 'active' : ''}`}
              onClick={() => seekTo(line.start)}
            >
              <span className="video-script-time">{formatTime(line.start)}</span>
              <span className="video-script-en">{line.text}</span>
              <span className="video-script-ko">{line.textKo}</span>
            </button>
          );
        })}
      </div>
    </section>
  );
}
