import { useCallback, useEffect, useRef, useState } from 'react';
import type { VideoCaptionLine } from '../types';
import { useYouTubePlayer } from '../hooks/useYouTubePlayer';
import { parseYoutubeVideoId } from '../utils/youtube';
import { fetchYoutubeCaptions } from '../utils/youtubeCaptions';
import { translateLinesToEnglish, translateLinesToKorean } from '../utils/translate';

function uid() {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function formatTime(sec: number) {
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m}:${s.toString().padStart(2, '0')}`;
}

export function VideoLearnTab() {
  const [url, setUrl] = useState('');
  const [videoId, setVideoId] = useState<string | null>(null);
  const [captions, setCaptions] = useState<VideoCaptionLine[]>([]);
  const [loading, setLoading] = useState(false);
  const [translating, setTranslating] = useState(false);
  const [translateProgress, setTranslateProgress] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [captionNotice, setCaptionNotice] = useState<string | null>(null);

  const playerHostRef = useRef<HTMLDivElement>(null);
  const scriptRef = useRef<HTMLDivElement>(null);

  const { ready, playing, currentTime, loadVideo, seekTo } = useYouTubePlayer(playerHostRef);

  const activeIndex = captions.findIndex(
    (c) => currentTime >= c.start && currentTime < c.start + c.duration,
  );

  useEffect(() => {
    if (activeIndex < 0 || !scriptRef.current) return;
    const el = scriptRef.current.querySelector<HTMLElement>(`[data-line="${activeIndex}"]`);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'center' });
    }
  }, [activeIndex]);

  const handlePlay = useCallback(async () => {
    const id = parseYoutubeVideoId(url);
    if (!id) {
      setError('YouTube 링크 또는 11자리 영상 ID를 입력해 주세요.');
      return;
    }

    setError(null);
    setCaptionNotice(null);
    setLoading(true);
    setCaptions([]);
    setVideoId(null);

    try {
      setVideoId(id);
      await loadVideo(id);

      const captionResult = await fetchYoutubeCaptions(id);
      if (!captionResult) {
        setCaptionNotice(
          '이 영상에는 YouTube 자막이 없어 영상만 재생됩니다. 자막·번역은 YouTube에 자막(자동 생성 포함)이 있는 영상에서 사용할 수 있습니다.',
        );
        return;
      }

      const { lines: raw, sourceLang, isAutoGenerated } = captionResult;
      const isKoreanSource = sourceLang === 'ko';

      const baseLines: VideoCaptionLine[] = raw.map((line) => ({
        ...line,
        id: uid(),
        text: isKoreanSource ? '번역 중…' : line.text,
        textKo: isKoreanSource ? line.text : '번역 중…',
      }));
      setCaptions(baseLines);

      if (isAutoGenerated) {
        setCaptionNotice('자동 생성 자막을 사용 중입니다.');
      }

      setTranslating(true);
      setTranslateProgress('0%');
      const translateJob = isKoreanSource
        ? translateLinesToEnglish(
            raw.map((c) => c.text),
            (done, total) => setTranslateProgress(`${Math.round((done / total) * 100)}%`),
          ).then((en) => {
            setCaptions((prev) =>
              prev.map((line, i) => ({ ...line, text: en[i] ?? line.text })),
            );
          })
        : translateLinesToKorean(
            raw.map((c) => c.text),
            (done, total) => setTranslateProgress(`${Math.round((done / total) * 100)}%`),
          ).then((ko) => {
            setCaptions((prev) =>
              prev.map((line, i) => ({ ...line, textKo: ko[i] ?? line.textKo })),
            );
          });

      void translateJob
        .catch(() => {
          setCaptions((prev) =>
            prev.map((line) => ({
              ...line,
              text: line.text === '번역 중…' ? '(번역 실패)' : line.text,
              textKo: line.textKo === '번역 중…' ? '(번역 실패)' : line.textKo,
            })),
          );
        })
        .finally(() => {
          setTranslating(false);
          setTranslateProgress('');
        });
    } catch (e) {
      setError(e instanceof Error ? e.message : '영상을 불러오지 못했습니다.');
      setVideoId(null);
    } finally {
      setLoading(false);
    }
  }, [url, loadVideo]);

  return (
    <section className="video-learn-tab">
      <div className="video-url-bar">
        <input
          type="url"
          className="video-url-input"
          placeholder="YouTube 링크 붙여넣기 (예: https://youtu.be/...)"
          value={url}
          onChange={(e) => setUrl(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && void handlePlay()}
          enterKeyHint="go"
          autoCapitalize="off"
          autoCorrect="off"
        />
        <button
          type="button"
          className="video-play-btn"
          onClick={() => void handlePlay()}
          disabled={loading || !url.trim()}
        >
          {loading ? '불러오는 중…' : '▶ 재생'}
        </button>
      </div>

      {error && <p className="video-error">{error}</p>}
      {captionNotice && !error && <p className="video-notice">{captionNotice}</p>}

      <div className="video-player-wrap">
        <div
          ref={playerHostRef}
          className={`video-player-host ${videoId ? 'active' : ''}`}
          aria-label="YouTube 영상 플레이어"
        />
        {!videoId && !loading && (
          <div className="video-player-placeholder">
            <span>🎬</span>
            <p>링크 입력 후 재생 버튼을 눌러 주세요</p>
            <small>자막이 있으면 영어·한국어 스크립트 표시 (자동 생성 자막 포함)</small>
          </div>
        )}
      </div>

      {videoId && (
        <div className="video-meta">
          <span>{ready ? (playing ? '재생 중' : '일시정지') : '플레이어 준비 중'}</span>
          {translating && <span className="video-translate-status">번역 {translateProgress}</span>}
        </div>
      )}

      <div className="video-script-panel" ref={scriptRef}>
        <h3 className="video-script-title">자막 · 번역</h3>
        {captions.length === 0 && !loading && videoId && (
          <p className="video-script-empty">자막이 없어 스크립트를 표시할 수 없습니다. 영상은 재생 중입니다.</p>
        )}
        {captions.length === 0 && !loading && !videoId && (
          <p className="video-script-empty">재생하면 자막과 번역이 표시됩니다.</p>
        )}
        {captions.map((line, index) => {
          const active = index === activeIndex;
          return (
            <button
              key={line.id}
              type="button"
              data-line={index}
              className={`video-script-line ${active ? 'active' : ''}`}
              onClick={() => {
                seekTo(line.start);
              }}
            >
              <span className="video-script-time">{formatTime(line.start)}</span>
              <span className="video-script-en">{line.text}</span>
              <span className="video-script-ko">{line.textKo}</span>
            </button>
          );
        })}
      </div>
    </section>
  );
}
