import type { VideoCaptionLine } from '../types';

const INNERTUBE_KEY = 'AIzaSyAO_FJ2SlqU8Q4STEHL6lNFOKAs_AhrUe8';

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string;
}

interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: { utf8?: string }[];
}

export type CaptionSourceLang = 'en' | 'ko' | 'other';

function trackPriority(t: CaptionTrack): number {
  const lc = t.languageCode.toLowerCase();
  const manual = t.kind !== 'asr';
  if (lc.startsWith('en') && manual) return 0;
  if (lc.startsWith('en')) return 1;
  if (lc.startsWith('ko') && manual) return 2;
  if (lc.startsWith('ko')) return 3;
  return manual ? 4 : 5;
}

function pickCaptionTrack(tracks: CaptionTrack[]): CaptionTrack | null {
  if (tracks.length === 0) return null;
  return [...tracks].sort((a, b) => trackPriority(a) - trackPriority(b))[0];
}

function detectSourceLang(code: string): CaptionSourceLang {
  const lc = code.toLowerCase();
  if (lc.startsWith('en')) return 'en';
  if (lc.startsWith('ko')) return 'ko';
  return 'other';
}

export async function hasYoutubeCaptions(videoId: string): Promise<boolean> {
  try {
    const tracks = await fetchCaptionTracks(videoId);
    return tracks.length > 0;
  } catch {
    return false;
  }
}

async function fetchCaptionTracks(videoId: string): Promise<CaptionTrack[]> {
  const res = await fetch(
    `https://www.youtube.com/youtubei/v1/player?key=${INNERTUBE_KEY}&prettyPrint=false`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        context: {
          client: { clientName: 'ANDROID', clientVersion: '19.09.37', hl: 'en', gl: 'US' },
        },
        videoId,
      }),
    },
  );

  if (!res.ok) throw new Error('영상 정보를 불러오지 못했습니다.');

  const data = (await res.json()) as {
    captions?: {
      playerCaptionsTracklistRenderer?: {
        captionTracks?: CaptionTrack[];
      };
    };
  };

  return data.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
}

function parseJson3Captions(json: { events?: Json3Event[] }): Omit<VideoCaptionLine, 'id' | 'textKo'>[] {
  const raw: { start: number; end: number; text: string }[] = [];

  for (const ev of json.events ?? []) {
    const text = (ev.segs ?? []).map((s) => s.utf8 ?? '').join('').replace(/\n/g, ' ').trim();
    if (!text) continue;
    const start = (ev.tStartMs ?? 0) / 1000;
    const end = start + (ev.dDurationMs ?? 0) / 1000;
    raw.push({ start, end, text });
  }

  if (raw.length === 0) return [];

  const merged: { start: number; end: number; text: string }[] = [];
  let cur = { ...raw[0] };

  for (let i = 1; i < raw.length; i++) {
    const next = raw[i];
    if (next.start - cur.end < 0.6 && cur.text.length + next.text.length < 120) {
      cur.text = `${cur.text} ${next.text}`.trim();
      cur.end = next.end;
    } else {
      merged.push(cur);
      cur = { ...next };
    }
  }
  merged.push(cur);

  return merged.map((m) => ({
    start: m.start,
    duration: Math.max(0.3, m.end - m.start),
    text: m.text,
  }));
}

async function downloadCaptionJson(track: CaptionTrack): Promise<{ events?: Json3Event[] }> {
  const url = track.baseUrl.includes('fmt=')
    ? track.baseUrl
    : `${track.baseUrl}&fmt=json3`;
  const res = await fetch(url);
  if (!res.ok) throw new Error('자막 파일을 불러오지 못했습니다.');
  return res.json() as Promise<{ events?: Json3Event[] }>;
}

export interface YoutubeCaptionResult {
  lines: Pick<VideoCaptionLine, 'start' | 'duration' | 'text'>[];
  sourceLang: CaptionSourceLang;
  isAutoGenerated: boolean;
}

/** 자막이 없으면 null (영상만 재생 가능) */
export async function fetchYoutubeCaptions(videoId: string): Promise<YoutubeCaptionResult | null> {
  const tracks = await fetchCaptionTracks(videoId);
  if (tracks.length === 0) return null;

  const track = pickCaptionTrack(tracks);
  if (!track) return null;

  const json = await downloadCaptionJson(track);
  const lines = parseJson3Captions(json);
  if (lines.length === 0) return null;

  return {
    lines,
    sourceLang: detectSourceLang(track.languageCode),
    isAutoGenerated: track.kind === 'asr',
  };
}
