"""여행 영어 회화 샘플 (단어카드 / 퀴즈용)."""

TRAVEL_PHRASES: list[tuple[str, str, str, str]] = [
    ("Where is the subway station?", "지하철역이 어디예요?", "Excuse me, where is the subway station?", "실례합니다, 지하철역이 어디예요?"),
    ("I'd like to check in", "체크인 하고 싶어요", "I'd like to check in, please.", "체크인 부탁드립니다."),
    ("I have a reservation", "예약했어요", "I have a reservation under Kim.", "김으로 예약했습니다."),
    ("How much is this?", "이거 얼마예요?", "How much is this souvenir?", "이 기념품은 얼마예요?"),
    ("Do you take credit cards?", "카드 되나요?", "Do you take credit cards?", "신용카드 받으시나요?"),
    ("Where is the boarding gate?", "탑승구가 어디예요?", "Where is boarding gate B12?", "B12 탑승구가 어디예요?"),
    ("My flight is delayed", "비행기가 연착됐어요", "My flight is delayed by two hours.", "비행기가 두 시간 연착됐어요."),
    ("I lost my passport", "여권을 잃어버렸어요", "I lost my passport. What should I do?", "여권을 잃어버렸어요. 어떻게 해야 하나요?"),
    ("Can you call a taxi?", "택시 불러 주실 수 있나요?", "Can you call a taxi for me?", "택시 좀 불러 주시겠어요?"),
    ("Is breakfast included?", "조식 포함인가요?", "Is breakfast included in the room?", "객실에 조식이 포함돼 있나요?"),
    ("I need a wake-up call", "모닝콜 부탁해요", "I need a wake-up call at seven.", "7시에 모닝콜 부탁합니다."),
    ("Where can I exchange money?", "환전은 어디서 해요?", "Where can I exchange money nearby?", "근처에서 환전할 곳이 어디예요?"),
    ("Is this seat taken?", "이 자리 있나요?", "Excuse me, is this seat taken?", "실례합니다, 이 자리 있나요?"),
    ("One ticket to downtown, please", "시내행 표 한 장 주세요", "One ticket to downtown, please.", "시내행 표 한 장 주세요."),
    ("Could you speak more slowly?", "좀 천천히 말씀해 주세요", "Could you speak more slowly, please?", "좀 천천히 말씀해 주시겠어요?"),
    ("I don't understand", "이해가 안 돼요", "I'm sorry, I don't understand.", "죄송해요, 이해가 안 돼요."),
    ("Can you recommend a restaurant?", "맛집 추천해 주세요", "Can you recommend a good restaurant?", "좋은 식당 추천해 주시겠어요?"),
    ("I'm allergic to nuts", "견과류 알레르기가 있어요", "I'm allergic to nuts.", "견과류 알레르기가 있습니다."),
    ("The check, please", "계산서 주세요", "The check, please.", "계산서 주세요."),
    ("Keep the change", "거스름돈은 가지세요", "Keep the change.", "거스름돈은 가지세요."),
    ("Where is the baggage claim?", "수하물 찾는 곳이 어디예요?", "Where is the baggage claim?", "수하물 찾는 곳이 어디예요?"),
    ("My luggage is missing", "제 짐이 없어졌어요", "My luggage didn't arrive.", "제 짐이 도착하지 않았어요."),
    ("I need a doctor", "의사가 필요해요", "I need to see a doctor.", "의사 진료를 받아야 해요."),
    ("Call the police", "경찰을 불러 주세요", "Please call the police.", "경찰을 불러 주세요."),
    ("Is it far from here?", "여기서 멀어요?", "Is the museum far from here?", "박물관이 여기서 멀어요?"),
    ("Turn left at the corner", "모퉁이에서 왼쪽으로 가세요", "Turn left at the next corner.", "다음 모퉁이에서 왼쪽으로 가세요."),
    ("How long does it take?", "얼마나 걸려요?", "How long does it take by bus?", "버스로 얼마나 걸려요?"),
    ("I'd like a window seat", "창가 자리로 주세요", "I'd like a window seat, please.", "창가 자리로 주세요."),
    ("What time is checkout?", "체크아웃이 몇 시예요?", "What time is checkout?", "체크아웃은 몇 시예요?"),
    ("Can I have a map?", "지도 하나 주세요", "Can I have a city map?", "시내 지도 하나 주시겠어요?"),
    ("Is there free Wi-Fi?", "무료 와이파이 있나요?", "Is there free Wi-Fi here?", "여기 무료 와이파이 있나요?"),
    ("I'm here for sightseeing", "관광 왔어요", "I'm here for sightseeing.", "관광하러 왔어요."),
    ("Take a picture, please", "사진 좀 찍어 주세요", "Could you take a picture, please?", "사진 좀 찍어 주시겠어요?"),
    ("It's beautiful here", "여기 정말 아름다워요", "It's beautiful here!", "여기 정말 아름다워요!"),
    ("I need a SIM card", "유심이 필요해요", "Where can I buy a SIM card?", "유심은 어디서 살 수 있나요?"),
    ("What is the Wi-Fi password?", "와이파이 비밀번호가 뭐예요?", "What is the Wi-Fi password?", "와이파이 비밀번호가 뭐예요?"),
    ("Room service, please", "룸서비스 부탁해요", "Room service, please.", "룸서비스 부탁합니다."),
    ("The air conditioning doesn't work", "에어컨이 안 돼요", "The air conditioning doesn't work.", "에어컨이 작동하지 않아요."),
    ("Can I get a refund?", "환불 가능한가요?", "Can I get a refund?", "환불 받을 수 있나요?"),
    ("Have a nice trip!", "즐거운 여행 되세요", "Thank you! Have a nice trip!", "감사합니다! 즐거운 여행 되세요!"),
]
