# 왕초보영어회화 TFnThlz9gaQ - 200 daily expressions (기초영어 Step by Step)
# https://www.youtube.com/watch?v=TFnThlz9gaQ

YOUTUBE_DAILY: list[tuple[str, str, str, str]] = [
    ("I take that back", "방금 한 말 취소할게", "I take that back.", "방금 한 말 취소할게."),
    ("my phone is missing", "내 폰이 없어졌어", "My phone is missing.", "내 폰이 없어졌어."),
    ("I'm falling apart", "나 완전 무너지고 있어", "I'm falling apart.", "나 완전 무너지고 있어."),
    ("coffee's on me", "커피는 내가 살게", "Coffee's on me.", "커피는 내가 살게."),
    ("I'm on a coffee break", "나 커피 마시면서 쉬는 중이야", "I'm on a coffee break.", "나 커피 마시면서 쉬는 중이야."),
    ("my skin is breaking out", "피부가 뒤집어졌어", "My skin is breaking out.", "피부가 뒤집어졌어."),
    ("the flu is going around", "독감이 돌고 있어", "The flu is going around.", "독감이 돌고 있어."),
    ("bundle up", "따뜻하게 입어", "Bundle up.", "따뜻하게 입어."),
    ("what's on your mind", "무슨 생각해?", "What's on your mind?", "무슨 생각해?"),
    ("let's catch up soon", "곧 근황 얘기하자", "Let's catch up soon.", "곧 근황 얘기하자."),
    ("I'm out of milk", "우유가 다 떨어졌어", "I'm out of milk.", "우유가 다 떨어졌어."),
    ("turn it over", "뒤집어 봐", "Turn it over.", "뒤집어 봐."),
    ("I have two kids", "아이가 둘이야", "I have two kids.", "아이가 둘이야."),
    ("I'm married", "나 결혼했어", "I'm married.", "나 결혼했어."),
    ("I'm single", "나 싱글이야", "I'm single.", "나 싱글이야."),
    ("cash or card", "현금이에요, 카드예요?", "Cash or card?", "현금이에요, 카드예요?"),
    ("I missed you a lot", "너무 보고 싶었어", "I missed you a lot.", "너무 보고 싶었어."),
    ("can I get a new one", "새 걸로 바꿀 수 있을까요?", "Can I get a new one?", "새 걸로 바꿀 수 있을까요?"),
    ("just leave me alone", "그냥 내버려 둬", "Just leave me alone.", "그냥 내버려 둬."),
    ("are you busy tomorrow", "내일 바빠?", "Are you busy tomorrow?", "내일 바빠?"),
    ("no I'm free all day", "아니, 하루 종일 한가해", "No, I'm free all day.", "아니, 하루 종일 한가해."),
    ("let's hang out then", "그럼 놀러 가자", "Let's hang out then.", "그럼 놀러 가자."),
    ("what's new with you", "요즘 어때?", "What's new with you?", "요즘 어때?"),
    ("not much", "별일 없어", "Not much.", "별일 없어."),
    ("what do you do", "무슨 일 해?", "What do you do?", "무슨 일 해?"),
    ("I work in sales", "나 영업 일 해", "I work in sales.", "나 영업 일 해."),
    ("I work in IT", "나 IT 일 해", "I work in IT.", "나 IT 일 해."),
    ("is it far from here", "여기서 멀어?", "Is it far from here?", "여기서 멀어?"),
    ("that's really interesting", "정말 재미있네", "That's really interesting.", "정말 재미있네."),
    ("I have a bad memory", "나 기억력이 나빠", "I have a bad memory.", "나 기억력이 나빠."),
    ("how about tomorrow", "내일은 어때?", "How about tomorrow?", "내일은 어때?"),
    ("do you need any help", "도움이 필요해?", "Do you need any help?", "도움이 필요해?"),
    ("it's raining outside", "밖에 비 와", "It's raining outside.", "밖에 비 와."),
    ("can we talk", "이야기 좀 할 수 있을까?", "Can we talk?", "이야기 좀 할 수 있을까?"),
    ("have a great time", "좋은 시간 보내", "Have a great time.", "좋은 시간 보내."),
    ("is there an extra charge", "추가 요금 있나요?", "Is there an extra charge?", "추가 요금 있나요?"),
    ("I'm just looking around", "그냥 둘러보는 중이에요", "I'm just looking around.", "그냥 둘러보는 중이에요."),
    ("what would you like", "뭘로 드릴까요?", "What would you like?", "뭘로 드릴까요?"),
    ("I like your outfit", "옷 스타일 좋다", "I like your outfit.", "옷 스타일 좋다."),
    ("my car ran out of gas", "차 기름이 다 떨어졌어", "My car ran out of gas.", "차 기름이 다 떨어졌어."),
    ("do you want a refill", "리필할래?", "Do you want a refill?", "리필할래?"),
    ("it's almost five o'clock", "거의 5시야", "It's almost five o'clock.", "거의 5시야."),
    ("it's challenging", "꽤 어렵네", "It's challenging.", "꽤 어렵네."),
    ("didn't I tell you", "내가 말했잖아", "Didn't I tell you?", "내가 말했잖아."),
    ("I look terrible in pictures", "사진 찍히면 안 예뻐", "I look terrible in pictures.", "사진 찍히면 안 예뻐."),
    ("are you done with that", "그거 다 했어?", "Are you done with that?", "그거 다 했어?"),
    ("you two know each other", "둘이 아는 사이야?", "You two know each other?", "둘이 아는 사이야?"),
    ("I'm sorry to bother you", "방해해서 미안해요", "I'm sorry to bother you.", "방해해서 미안해요."),
    ("which one do you prefer", "어느 쪽이 더 좋아?", "Which one do you prefer?", "어느 쪽이 더 좋아?"),
    ("let's have dinner together", "같이 저녁 먹자", "Let's have dinner together.", "같이 저녁 먹자."),
    ("let's get some coffee", "커피 마시러 가자", "Let's get some coffee.", "커피 마시러 가자."),
    ("what happened", "무슨 일이야?", "What happened?", "무슨 일이야?"),
    ("can I take photos here", "여기서 사진 찍어도 돼요?", "Can I take photos here?", "여기서 사진 찍어도 돼요?"),
    ("what can I get you", "뭘 드릴까요?", "What can I get you?", "뭘 드릴까요?"),
    ("this shirt goes with everything", "이 셔츠는 뭐든 잘 어울려", "This shirt goes with everything.", "이 셔츠는 뭐든 잘 어울려."),
    ("this is so sweet", "너무 달콤하다", "This is so sweet.", "너무 달콤하다."),
    ("I want to visit new places", "새로운 곳을 가보고 싶어", "I want to visit new places.", "새로운 곳을 가보고 싶어."),
    ("can I have a menu", "메뉴 좀 주세요", "Can I have a menu?", "메뉴 좀 주세요."),
    ("it's boring", "지루해", "It's boring.", "지루해."),
    ("I think I have a cold", "감기 걸린 것 같아", "I think I have a cold.", "감기 걸린 것 같아."),
    ("I'd love to do that", "그거 하고 싶어", "I'd love to do that.", "그거 하고 싶어."),
    ("you look great", "멋져 보여", "You look great.", "멋져 보여."),
    ("step back please", "잠깐 뒤로 물러나 주세요", "Step back please.", "잠깐 뒤로 물러나 주세요."),
    ("what's on TV", "TV에 뭐 나와?", "What's on TV?", "TV에 뭐 나와?"),
    ("feel free to drop by", "언제든 들러도 돼", "Feel free to drop by.", "언제든 들러도 돼."),
    ("what should we do", "뭘 할까?", "What should we do?", "뭘 할까?"),
    ("let's go out for dinner", "저녁 먹으러 나가자", "Let's go out for dinner.", "저녁 먹으러 나가자."),
    ("can I change my order", "주문 변경할 수 있을까요?", "Can I change my order?", "주문 변경할 수 있을까요?"),
    ("I have a runny nose", "콧물이 나", "I have a runny nose.", "콧물이 나."),
    ("let me think about it", "생각해 볼게", "Let me think about it.", "생각해 볼게."),
    ("what do you like to do", "뭘 하는 걸 좋아해?", "What do you like to do?", "뭘 하는 걸 좋아해?"),
    ("do you need anything", "필요한 거 있어?", "Do you need anything?", "필요한 거 있어?"),
    ("I'll have a latte", "라떼 주세요", "I'll have a latte.", "라떼 주세요."),
    ("come in", "들어와", "Come in.", "들어와."),
    ("stop showing off", "잘난 체 그만해", "Stop showing off.", "잘난 체 그만해."),
    ("I don't like sweets", "단 건 별로야", "I don't like sweets.", "단 건 별로야."),
    ("I love this place", "이 장소 정말 좋아", "I love this place.", "이 장소 정말 좋아."),
    ("I have a meeting today", "오늘 회의가 있어", "I have a meeting today.", "오늘 회의가 있어."),
    ("can I have the bill", "계산서 주세요", "Can I have the bill?", "계산서 주세요."),
    ("I'll come back later", "나중에 다시 올게", "I'll come back later.", "나중에 다시 올게."),
    ("you look great today", "오늘 정말 멋져 보여", "You look great today.", "오늘 정말 멋져 보여."),
    ("how long will it take", "얼마나 걸려?", "How long will it take?", "얼마나 걸려?"),
    ("have we met before", "전에 만난 적 있나?", "Have we met before?", "전에 만난 적 있나?"),
    ("I don't have enough time", "시간이 충분하지 않아", "I don't have enough time.", "시간이 충분하지 않아."),
    ("have a good weekend", "좋은 주말 보내", "Have a good weekend.", "좋은 주말 보내."),
    ("have a good day", "좋은 하루 보내", "Have a good day.", "좋은 하루 보내."),
    ("are you going to come", "올 거야?", "Are you going to come?", "올 거야?"),
    ("what's wrong with you", "무슨 일이야?", "What's wrong with you?", "무슨 일이야?"),
    ("can I have a coffee", "커피 한 잔 주세요", "Can I have a coffee?", "커피 한 잔 주세요."),
    ("are you a morning person", "아침형 인간이야?", "Are you a morning person?", "아침형 인간이야?"),
    ("I'm a vegetarian", "나 채식주의자야", "I'm a vegetarian.", "나 채식주의자야."),
    ("I'm going on vacation", "휴가 가", "I'm going on vacation.", "휴가 가."),
    ("are you all right", "괜찮아?", "Are you all right?", "괜찮아?"),
    ("I'm so tired", "너무 피곤해", "I'm so tired.", "너무 피곤해."),
    ("you're doing a great job", "정말 잘하고 있어", "You're doing a great job.", "정말 잘하고 있어."),
    ("want to try some", "좀 먹어 볼래?", "Want to try some?", "좀 먹어 볼래?"),
    ("I'll think about it", "생각해 볼게", "I'll think about it.", "생각해 볼게."),
    ("here you go", "여기 있어요", "Here you go.", "여기 있어요."),
    ("is this seat taken", "이 자리 있나요?", "Is this seat taken?", "이 자리 있나요?"),
    ("I'm not interested at all", "전혀 관심 없어", "I'm not interested at all.", "전혀 관심 없어."),
    ("let's enjoy this moment", "이 순간을 즐기자", "Let's enjoy this moment.", "이 순간을 즐기자."),
    ("I couldn't sleep a wink", "한숨도 못 잤어", "I couldn't sleep a wink.", "한숨도 못 잤어."),
    ("I had a great time", "정말 좋은 시간이었어", "I had a great time.", "정말 좋은 시간이었어."),
    ("are you sure about that", "확실해?", "Are you sure about that?", "확실해?"),
    ("who told you that", "누가 그렇게 말했어?", "Who told you that?", "누가 그렇게 말했어?"),
    ("for here or to go", "여기서 드시나요, 포장인가요?", "For here or to go?", "여기서 드시나요, 포장인가요?"),
    ("he's not coming back", "그는 돌아오지 않을 거야", "He's not coming back.", "그는 돌아오지 않을 거야."),
    ("I broke up with him", "그와 헤어졌어", "I broke up with him.", "그와 헤어졌어."),
    ("I'm not a night owl", "나는 올빼미족이 아니야", "I'm not a night owl.", "나는 올빼미족이 아니야."),
    ("I enjoy taking selfies", "셀카 찍는 걸 좋아해", "I enjoy taking selfies.", "셀카 찍는 걸 좋아해."),
    ("can I have that to go", "포장해 주세요", "Can I have that to go?", "포장해 주세요."),
    ("I need a break", "쉬어야겠어", "I need a break.", "쉬어야겠어."),
    ("no thanks I will pass", "괜찮아요, 사양할게요", "No thanks, I will pass.", "괜찮아요, 사양할게요."),
    ("I don't care", "상관없어", "I don't care.", "상관없어."),
    ("are you busy right now", "지금 바빠?", "Are you busy right now?", "지금 바빠?"),
    ("I'll keep that in mind", "기억해 둘게", "I'll keep that in mind.", "기억해 둘게."),
    ("is it your birthday", "오늘 생일이야?", "Is it your birthday?", "오늘 생일이야?"),
    ("are you coming", "올 거야?", "Are you coming?", "올 거야?"),
    ("I'll take this", "이걸로 할게요", "I'll take this.", "이걸로 할게요."),
    ("I'll have the same", "저도 같은 걸로요", "I'll have the same.", "저도 같은 걸로요."),
    ("can I check in now", "지금 체크인할 수 있나요?", "Can I check in now?", "지금 체크인할 수 있나요?"),
    ("do you have your cell phone", "휴대폰 있어?", "Do you have your cell phone?", "휴대폰 있어?"),
    ("I work out every day", "매일 운동해", "I work out every day.", "매일 운동해."),
    ("that'll be five dollars", "5달러입니다", "That'll be five dollars.", "5달러입니다."),
    ("when did you break up", "언제 헤어졌어?", "When did you break up?", "언제 헤어졌어?"),
    ("I love sleeping in", "늦잠 자는 걸 좋아해", "I love sleeping in.", "늦잠 자는 걸 좋아해."),
    ("that's a great photo", "사진 정말 잘 나왔다", "That's a great photo.", "사진 정말 잘 나왔다."),
    ("I have two sisters", "언니/누나가 둘이야", "I have two sisters.", "언니/누나가 둘이야."),
    ("I'm feeling stressed", "스트레스 받아", "I'm feeling stressed.", "스트레스 받아."),
    ("that would be nice", "그거 좋겠다", "That would be nice.", "그거 좋겠다."),
    ("I need more time", "시간이 더 필요해", "I need more time.", "시간이 더 필요해."),
    ("how about you", "너는?", "How about you?", "너는?"),
    ("I ache all over", "온몸이 쑤셔", "I ache all over.", "온몸이 쑤셔."),
    ("there's no need to hurry", "서두를 필요 없어", "There's no need to hurry.", "서두를 필요 없어."),
    ("are you free tonight", "오늘 밤 시간 돼?", "Are you free tonight?", "오늘 밤 시간 돼?"),
    ("are you free this weekend", "이번 주말에 시간 돼?", "Are you free this weekend?", "이번 주말에 시간 돼?"),
    ("I'm so happy for you", "정말 축하해", "I'm so happy for you.", "정말 축하해."),
    ("I am freaking out", "완전 패닉이야", "I am freaking out.", "완전 패닉이야."),
    ("my back is killing me", "허리가 너무 아파", "My back is killing me.", "허리가 너무 아파."),
    ("what time is it now", "지금 몇 시야?", "What time is it now?", "지금 몇 시야?"),
    ("do you mind if I sit here", "여기 앉아도 될까요?", "Do you mind if I sit here?", "여기 앉아도 될까요?"),
    ("I turned it off", "껐어", "I turned it off.", "껐어."),
    ("I just moved in", "방금 이사 왔어", "I just moved in.", "방금 이사 왔어."),
    ("I enjoy spring", "봄이 좋아", "I enjoy spring.", "봄이 좋아."),
    ("I'm the oldest", "나가 맏이야", "I'm the oldest.", "나가 맏이야."),
    ("I'm sorry about that", "그건 미안해", "I'm sorry about that.", "그건 미안해."),
    ("it doesn't matter", "상관없어", "It doesn't matter.", "상관없어."),
    ("I'm really bored", "정말 지루해", "I'm really bored.", "정말 지루해."),
    ("it's too greasy", "너무 기름져", "It's too greasy.", "너무 기름져."),
    ("what's the matter", "무슨 일이야?", "What's the matter?", "무슨 일이야?"),
    ("have you been there", "거기 가 봤어?", "Have you been there?", "거기 가 봤어?"),
    ("I've been there a few times", "거기 몇 번 가 봤어", "I've been there a few times.", "거기 몇 번 가 봤어."),
    ("I can't hear you", "잘 안 들려", "I can't hear you.", "잘 안 들려."),
    ("am I late", "늦었어?", "Am I late?", "늦었어?"),
    ("are you serious", "진심이야?", "Are you serious?", "진심이야?"),
    ("I'll pay in cash", "현금으로 낼게", "I'll pay in cash.", "현금으로 낼게."),
    ("I got a cold", "감기 걸렸어", "I got a cold.", "감기 걸렸어."),
    ("I have no choice", "선택의 여지가 없어", "I have no choice.", "선택의 여지가 없어."),
    ("it was nice meeting you", "만나서 반가웠어", "It was nice meeting you.", "만나서 반가웠어."),
    ("I'm on a diet", "다이어트 중이야", "I'm on a diet.", "다이어트 중이야."),
    ("please turn off your phone", "휴대폰 꺼 주세요", "Please turn off your phone.", "휴대폰 꺼 주세요."),
    ("I'm at home", "집에 있어", "I'm at home.", "집에 있어."),
    ("let's go for a walk", "산책하러 가자", "Let's go for a walk.", "산책하러 가자."),
    ("I like sunny days", "맑은 날이 좋아", "I like sunny days.", "맑은 날이 좋아."),
    ("what are friends for", "친구 좋은 건 뭐야", "What are friends for?", "친구 좋은 건 뭐야."),
    ("how can I get there", "거기 어떻게 가?", "How can I get there?", "거기 어떻게 가?"),
    ("I'll let you know later", "나중에 알려줄게", "I'll let you know later.", "나중에 알려줄게."),
    ("you're such a good friend", "정말 좋은 친구야", "You're such a good friend.", "정말 좋은 친구야."),
    ("I'm with you", "네 편이야", "I'm with you.", "네 편이야."),
    ("can I see your ID", "신분증 보여주시겠어요?", "Can I see your ID?", "신분증 보여주시겠어요?"),
    ("I have booked online", "온라인으로 예약했어요", "I have booked online.", "온라인으로 예약했어요."),
    ("did you sleep well", "잘 잤어?", "Did you sleep well?", "잘 잤어?"),
    ("let's grab a snack", "간식 먹자", "Let's grab a snack.", "간식 먹자."),
    ("I was lucky", "운이 좋았어", "I was lucky.", "운이 좋았어."),
    ("sorry about that", "그건 미안해", "Sorry about that.", "그건 미안해."),
    ("I work from home", "재택근무해", "I work from home.", "재택근무해."),
    ("why didn't you tell me", "왜 나한테 말 안 했어?", "Why didn't you tell me?", "왜 나한테 말 안 했어?"),
    ("let's get out of here", "여기서 나가자", "Let's get out of here.", "여기서 나가자."),
    ("where should I go", "어디로 가야 해?", "Where should I go?", "어디로 가야 해?"),
    ("let's get some air", "바깥 공기 좀 쐬자", "Let's get some air.", "바깥 공기 좀 쐬자."),
    ("do you have any allergies", "알레르기 있어?", "Do you have any allergies?", "알레르기 있어?"),
    ("I can't get Wi-Fi", "와이파이가 안 돼", "I can't get Wi-Fi.", "와이파이가 안 돼."),
    ("are you kidding me", "농담하는 거지?", "Are you kidding me?", "농담하는 거지?"),
    ("get some rest", "좀 쉬어", "Get some rest.", "좀 쉬어."),
    ("can I charge my phone", "휴대폰 충전해도 돼요?", "Can I charge my phone?", "휴대폰 충전해도 돼요?"),
    ("let's keep in touch", "연락하고 지내자", "Let's keep in touch.", "연락하고 지내자."),
    ("let's not talk about it", "그 얘기는 그만하자", "Let's not talk about it.", "그 얘기는 그만하자."),
    ("dinner is on me", "저녁은 내가 살게", "Dinner is on me.", "저녁은 내가 살게."),
    ("turn the steak over", "스테이크 뒤집어", "Turn the steak over.", "스테이크 뒤집어."),
    ("I'm a fan of novels", "소설을 좋아해", "I'm a fan of novels.", "소설을 좋아해."),
    ("I understand", "이해했어", "I understand.", "이해했어."),
    ("do you like your job", "일이 마음에 들어?", "Do you like your job?", "일이 마음에 들어?"),
    ("don't blame me", "나한테 화내지 마", "Don't blame me.", "나한테 화내지 마."),
    ("I love watching films", "영화 보는 걸 좋아해", "I love watching films.", "영화 보는 걸 좋아해."),
    ("I've been to Europe", "유럽에 가 봤어", "I've been to Europe.", "유럽에 가 봤어."),
    ("it's a bestseller", "베스트셀러야", "It's a bestseller.", "베스트셀러야."),
    ("are you close to them", "그들과 가까워?", "Are you close to them?", "그들과 가까워?"),
    ("yes we get along well", "응, 우리 사이좋아", "Yes, we get along well.", "응, 우리 사이좋아."),
    ("I'm into rock music", "록 음악을 좋아해", "I'm into rock music.", "록 음악을 좋아해."),
    ("ice cream is my weakness", "아이스크림은 못 참아", "Ice cream is my weakness.", "아이스크림은 못 참아."),
]
